### ISSUE TITLE
docker-compose自定义psql出错

### ISSUE THREAD

**Issue by huawuhen** [HiveNexus/HiveChat#68]
- 因为不想VPS上安装postgres，看到docker hub上有作者的镜像，自己写了个compose，运行却报错

## yml
```
services:
  app:
    container_name: hivechat
    image: hivenexus/hivechat
    ports:
      - "8082:3000"
    environment:
      DATABASE_URL: "postgres://kxxxxdm:xxxxxoO@ep-snowy-firefly-a1g5ugxj.ap-southeast-1.pg.koyeb.app/koyebdb"
      AUTH_SECRET: "hclqD3n21MphLevxGWsUnGU6BaEa2TjrCQ77weOVpPg="
      ADMIN_CODE: "2233"
      NEXTAUTH_URL: "http://127.0.0.1:8082"
      AUTH_TRUST_HOST: "TURE"
      EMAIL_AUTH_STATUS: "ON"
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
```

## 报错Logs

```
hivechat  |   ▲ Next.js 14.2.25
hivechat  |   - Local:        http://065f3855dcf7:3000
hivechat  |   - Network:      http://172.19.0.2:3000
hivechat  | 
hivechat  |  ✓ Starting...
hivechat  |  ✓ Ready in 151ms
hivechat  | c: connection is insecure (try using `sslmode=require`)
hivechat  |     at Q (/app/.next/server/chunks/6437.js:40:2291)
hivechat  |     at /app/.next/server/chunks/6437.js:40:3333
hivechat  |     at Socket.eB (/app/.next/server/chunks/6437.js:40:3338)
hivechat  |     at Socket.emit (node:events:518:28)
hivechat  |     at addChunk (node:internal/streams/readable:561:12)
hivechat  |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
hivechat  |     at Readable.push (node:internal/streams/readable:392:5)
hivechat  |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
hivechat  |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
hivechat  |   severity_local: 'ERROR',
hivechat  |   code: 'XX000',
hivechat  |   digest: '1453119709'
hivechat  | }
hivechat  | c: connection is insecure (try using `sslmode=require`)
hivechat  |     at Q (/app/.next/server/chunks/6437.js:40:2291)
hivechat  |     at /app/.next/server/chunks/6437.js:40:3333
hivechat  |     at Socket.eB (/app/.next/server/chunks/6437.js:40:3338)
hivechat  |     at Socket.emit (node:events:518:28)
hivechat  |     at addChunk (node:internal/streams/readable:561:12)
hivechat  |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
hivechat  |     at Readable.push (node:internal/streams/readable:392:5)
hivechat  |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
hivechat  |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
hivechat  |   severity_local: 'ERROR',
hivechat  |   code: 'XX000',
hivechat  |   digest: '1453119709'
hivechat  | }
hivechat  | c: connection is insecure (try using `sslmode=require`)
hivechat  |     at Q (/app/.next/server/chunks/6437.js:40:2291)
hivechat  |     at /app/.next/server/chunks/6437.js:40:3333
hivechat  |     at Socket.eB (/app/.next/server/chunks/6437.js:40:3338)
hivechat  |     at Socket.emit (node:events:518:28)
hivechat  |     at addChunk (node:internal/streams/readable:561:12)
hivechat  |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
hivechat  |     at Readable.push (node:internal/streams/readable:392:5)
hivechat  |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
hivechat  |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
hivechat  |   severity_local: 'ERROR',
hivechat  |   code: 'XX000',
hivechat  |   digest: '1453119709'
hivechat  | }
```
